import { resolveCurrentAgentEvent } from './currentAgentMechanicContracts'
import type { PlanningEventUsage } from './planningCalculationContextCompiler'
import {
  compileReviewedClaretHeldAction32,
  reviewedClaretHeldActionIdentity32,
} from './reviewedClaretHeldAction32'
import { resolveSourceEventQuantity32 } from './sourceEventQuantity32'

export const reviewedClaretFixedBenchmarkIdentity32 = Object.freeze({
  revision: 'claret-authored-six-maim-coefficient-benchmark-r1',
  commit: '6e75367eb5870765432f0c72a2db48fba01e4d8f',
  source:
    'https://github.com/ZztIsolation/zzz_calculator/blob/6e75367eb5870765432f0c72a2db48fba01e4d8f/data/agents.json',
  locator: 'claret.defaultCalculationConfig: custom / 双连携六毁伤',
  unit: 'coefficient_uses',
  kitCommit: reviewedClaretHeldActionIdentity32.kitCommit,
  adaptation: 'complete-held-upward-slash-twice; existing declared enemy and 30s baseline',
})

/** Adopt the author's fixed coefficient inventory, rather than treating a
 * different guide's variable until-Gash endpoint as the same action packet.
 * This inventory is not a resource/timing certificate for a combat rotation. */
export function compileReviewedClaretFixedBenchmark32(input: {
  mindscape: number
  potential?: number | null
  coreLevel: number
  skillLevels: Readonly<Record<string, number | null>>
}) {
  const blockers: string[] = []
  if (!Number.isInteger(input.mindscape) || input.mindscape < 0 || input.mindscape > 5)
    blockers.push('source_six_maim_inventory_requires_mindscape_0_to_5')
  if (input.potential != null && input.potential !== 0)
    blockers.push('source_six_maim_inventory_requires_potential_0')
  if (input.coreLevel !== 7) blockers.push('source_six_maim_inventory_requires_core_f')
  for (const skill of ['basic', 'special', 'chain']) {
    const level = input.skillLevels[skill]
    if (!Number.isInteger(level) || Number(level) < 1 || Number(level) > 16)
      blockers.push(`explicit_skill_level_required:${skill}`)
  }
  const rows = [
    // The source held group omits the upward slash. Our independently reviewed
    // complete-held contract includes it once, so record that adaptation.
    ['special.SpecialAttackBloodbloomOathCleavingGoldAndIron.hit-0', 'special', 2],
    ['special.SpecialAttackBloodbloomOathBloodBurialAssault.hit-0', 'special', 2],
    ['special.SpecialAttackBloodbloomOathCleavingGoldAndIron.hit-2', 'special', 6],
    ['basic.BasicAttackBloodbloomOathSubduingAxe.hit-0', 'basic', 2],
    ['basic.BasicAttackBloodbloomOathStarforging.hit-2', 'basic', 2],
    ['basic.BasicAttackBloodbloomOathStarforging.hit-3', 'basic', 2],
    ['chain.ChainAttackBloodbloomOathResonantBloodPact.hit-0', 'chain', 2],
    ['chain.UltimateBloodbloomOathTrialAfterTrial.hit-0', 'chain', 1],
  ] as const
  const eventUsages: PlanningEventUsage[] = rows.map(([eventId, skill, occurrenceCount]) => ({
    ownerAgentId: 'agent-claret',
    eventId,
    occurrenceCount,
    skillLevel: Number(input.skillLevels[skill]),
    evidenceRefs: [
      reviewedClaretFixedBenchmarkIdentity32.source,
      reviewedClaretFixedBenchmarkIdentity32.locator,
      ...(eventId === rows[0][0] ? [reviewedClaretHeldActionIdentity32.contractRef] : []),
      'source-measure:coefficient-uses; declared-benchmark-not-resource-simulation',
    ],
  }))
  if (!blockers.length)
    for (const usage of eventUsages) {
      const resolved = resolveCurrentAgentEvent({ stableId: usage.ownerAgentId, ...usage })
      if (
        resolved.status !== 'supported' ||
        resolved.source.commit !== reviewedClaretFixedBenchmarkIdentity32.kitCommit ||
        resolved.formulaFamily !== 'sharp_damage' ||
        resolved.scalingAttribute !== 'def' ||
        resolved.attribute !== 'electric' ||
        resolved.formulaProjection !== 'source_registered' ||
        resolveSourceEventQuantity32(usage).status !== 'supported'
      )
        blockers.push(`shared_source_event_contract_mismatch:${usage.eventId}`)
    }
  if (blockers.length)
    return { status: 'unsupported' as const, blockers, eventUsages: [] as PlanningEventUsage[] }
  return {
    status: 'supported' as const,
    eventUsages,
    sourceIdentity: reviewedClaretFixedBenchmarkIdentity32,
    resourceLegality: null,
    timingAuthority: 'existing_declared_benchmark' as const,
    formalCyclePromotion: false as const,
    boundary:
      '采用来源双连携六毁伤的固定系数组：完整长按两组、作者普攻系数组两组、连携两次和终结一次；补齐两次上挑。按当前声明敌人、恒定效果及30秒比较窗口计算，不代表完整整队轮转；普攻持有终点、残痕收支及动作耗时尚未与该系数组绑定，作者的失衡标签不作为实测事实。',
  }
}

/** A finite, kit-defined comparison, independent of the variable Basic3 route.
 * Its declared comparison duration is not the animation's measured duration.
 * Gash generated by the last Basic is unused; no subsequent spender or repeat
 * is inferred from its unknown fractional remainder. */
export function compileReviewedClaretPreparedBenchmark32(input: {
  mindscape: number
  potential?: number | null
  coreLevel: number
  skillLevels: Readonly<Record<string, number | null>>
}) {
  const blockers: string[] = []
  if (!Number.isInteger(input.mindscape) || input.mindscape < 0 || input.mindscape > 6)
    blockers.push('unsupported_mindscape')
  if (input.potential != null && input.potential !== 0)
    blockers.push('prepared_claret_requires_potential_0')
  if (!Number.isInteger(input.coreLevel) || input.coreLevel < 1 || input.coreLevel > 7)
    blockers.push('explicit_core_level_required')
  const basicLevel = input.skillLevels.basic
  if (!Number.isInteger(basicLevel) || Number(basicLevel) < 1 || Number(basicLevel) > 16)
    blockers.push('explicit_skill_level_required:basic')
  const held = compileReviewedClaretHeldAction32({
    skillLevel: Number(input.skillLevels.special ?? Number.NaN),
    preparedState: { crimsonInscription: true, targetGash: 3 },
    conditions: {
      upwardSlashContact: true,
      completeBloodBurialContact: true,
      heldMaimContacts: 3,
      constantDamageState: true,
      uninterruptedBloodBurial: true,
    },
  })
  if (held.status !== 'supported') blockers.push(...held.reasons)
  const source = reviewedClaretHeldActionIdentity32
  const axe: PlanningEventUsage = {
    ownerAgentId: 'agent-claret',
    eventId: 'basic.BasicAttackBloodbloomOathSubduingAxe.hit-0',
    skillLevel: Number(basicLevel),
    occurrenceCount: 1,
    evidenceRefs: [
      `${source.kitCommit}:${source.sourcePath}`,
      `${source.kitCommit}:${source.localizationPath}#/basic/BasicAttackBloodbloomOathSubduingAxe/desc`,
      'source-measure:complete-alternate-basic-once-after-maim-special',
    ],
  }
  const resolved = resolveCurrentAgentEvent({ stableId: 'agent-claret', ...axe })
  if (
    resolved.status !== 'supported' ||
    resolved.source.commit !== source.kitCommit ||
    resolved.formulaFamily !== 'sharp_damage' ||
    resolved.scalingAttribute !== 'def' ||
    resolved.attribute !== 'electric' ||
    resolved.damageType !== 'basic' ||
    resolved.formulaProjection !== 'source_registered' ||
    resolveSourceEventQuantity32(axe).status !== 'supported'
  )
    blockers.push('shared_source_event_contract_mismatch:subduing_axe')
  if (blockers.length || held.status !== 'supported')
    return { status: 'unsupported' as const, blockers, eventUsages: [] as PlanningEventUsage[] }
  return {
    status: 'supported' as const,
    eventUsages: [...held.eventUsages, axe],
    sourceIdentity: {
      ...source,
      revision: 'claret-prepared-held-subduing-axe-fixed-benchmark-r1',
      scope: 'personal-M0-M6-P0-core1-to7-finite-prepared-fixed-events',
    },
    resourceLegality: {
      ...held.resourceLegality,
      actionOrder: ['complete_held_three_maim', 'complete_subduing_axe'] as const,
      followUpQualification: 'maim_triggered_by_preceding_special' as const,
      followingGashConsumers: 0,
      // This is the state immediately after held, not a claim that the last
      // Basic cannot build new Gash. Its ending meter is unused by this set.
      targetGashAfterHeld: 0,
      terminalTargetGash: { exact: null, range: [0, 3] as const, consumedAgain: false },
      sameTarget: true,
      constantDamageState: true,
      noInterveningAction: true,
    },
    timingAuthority: 'declared_duration_static_effect_coverage' as const,
    boundary:
      '30秒为声明比较时长，计猩红铭刻和同目标三层斩痕准备态的一次完整长按三毁伤，再接一次伏钺；全部接触、效果状态恒定，准备动作伤害不计入。末次普攻的新斩痕不再消费，不外推续转或实测耗时，不代表完整整队轮转。',
  }
}
