import type { AgentRule } from './contracts'
import {
  zhuYuanGuide,
  qingyiGuide,
  astraGuide,
  yixuanGuide,
  panGuide,
  luciaGuide,
  dialynGuide,
  yixuanLuciaDialynSeed,
  yeGuide,
  zhaoGuide,
  sunnaGuide,
  ariaGuide,
  yuzuhaGuide,
  promeiaGuide,
  nangongGuide,
  pyroisGuide,
  normaTeamGuide,
  ultraJakeGuide,
  sproutAdoption,
} from './current31D1EvidenceRefs'

export const d1AgentRules: AgentRule[] = [
  {
    agentId: 'agent-zhu-yuan',
    name: '朱鸢',
    releaseState: 'released',
    specialty: 'damage',
    faction: '新艾利都治安局',
    attribute: 'ether',
    fieldTimeDemand: 0.55,
    produces: ['enhanced_shells', 'ether_burst'],
    consumes: ['enhanced_shells', 'stun_window'],
    effects: [],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
          { kind: 'faction_count', faction: '新艾利都治安局', minimum: 2 },
        ],
      },
      description: '需要支援或同阵营队友。',
    },
    evidence: [zhuYuanGuide],
  },
  {
    agentId: 'agent-qingyi',
    name: '青衣',
    releaseState: 'released',
    specialty: 'stun',
    faction: '新艾利都治安局',
    attribute: 'electric',
    fieldTimeDemand: 0.6,
    produces: ['stun_window', 'stun_multiplier', 'voltage'],
    consumes: ['voltage'],
    effects: [{ tag: 'stun_multiplier', recipient: 'enemy' }],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'damage', minimum: 1 },
          { kind: 'faction_count', faction: '新艾利都治安局', minimum: 2 },
        ],
      },
      description: '需要强攻或同阵营队友。',
    },
    evidence: [qingyiGuide],
  },
  {
    agentId: 'agent-astra',
    name: '耀嘉音',
    releaseState: 'released',
    specialty: 'support',
    faction: '天琴座',
    attribute: 'ether',
    fieldTimeDemand: 0.1,
    produces: ['team_attack', 'team_damage', 'quick_assist', 'chain_attack_refill'],
    consumes: [],
    effects: [
      { tag: 'team_attack', recipient: 'team' },
      { tag: 'team_damage', recipient: 'team' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'damage', minimum: 1 },
          { kind: 'specialty_count', specialty: 'anomaly', minimum: 1 },
          { kind: 'specialty_count', specialty: 'rupture', minimum: 1 },
        ],
      },
      description: '需要强攻、异常或命破队友。',
    },
    evidence: [astraGuide],
  },
  {
    agentId: 'agent-yixuan',
    name: '仪玄',
    releaseState: 'released',
    specialty: 'rupture',
    faction: '云岿山',
    attribute: 'ether',
    fieldTimeDemand: 0.8,
    produces: ['adrenaline', 'sheer_damage', 'auric_ink_corruption'],
    consumes: ['adrenaline'],
    effects: [],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'stun', minimum: 1 },
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
          { kind: 'specialty_count', specialty: 'defense', minimum: 1 },
        ],
      },
      description: '需要击破、支援或防护队友。',
    },
    evidence: [yixuanGuide],
  },
  {
    agentId: 'agent-pan-yinhu',
    name: '潘引壶',
    releaseState: 'released',
    specialty: 'defense',
    faction: '云岿山',
    attribute: 'physical',
    fieldTimeDemand: 0.15,
    produces: ['sheer_force_buff', 'adrenaline', 'quick_assist'],
    consumes: [],
    effects: [
      { tag: 'sheer_force_buff', recipient: 'active_agent' },
      { tag: 'damage_taken_debuff', recipient: 'enemy' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'rupture', minimum: 1 },
          { kind: 'faction_count', faction: '云岿山', minimum: 2 },
        ],
      },
      description: '需要命破或同阵营队友。',
    },
    evidence: [panGuide],
  },
  {
    agentId: 'agent-lucia',
    name: '卢西娅',
    releaseState: 'released',
    specialty: 'support',
    faction: '怪啖屋',
    attribute: 'ether',
    fieldTimeDemand: 0.2,
    produces: ['ether_veil', 'rupture_amplification', 'quick_assist'],
    consumes: [],
    effects: [{ tag: 'rupture_amplification', recipient: 'team' }],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'rupture', minimum: 1 },
          { kind: 'specialty_count', specialty: 'stun', minimum: 1 },
        ],
      },
      description: '需要命破或击破队友触发额外能力。',
    },
    evidence: [
      luciaGuide,
      yixuanLuciaDialynSeed,
      {
        sourceId: 'miyoushe-75217294-lucia-additional-ability',
        gameVersion: '2.8',
        status: 'candidate',
        locator:
          'https://www.miyoushe.com/zzz/article/75217294; op61 image252936807; imageSha256=f79f9da41ba490b4dc5813794d862a7b1a908eb545e211da19302f2dfa0af316; 触发条件：队伍中存在命破/击破角色',
      },
    ],
  },
  {
    agentId: 'agent-dialyn',
    name: '琉音',
    releaseState: 'released',
    specialty: 'stun',
    faction: '坎卜斯黑枝',
    attribute: 'physical',
    fieldTimeDemand: 0.3,
    produces: ['stun_window', 'ultimate_conversion'],
    consumes: [],
    effects: [{ tag: 'stun_multiplier', recipient: 'enemy' }],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'damage', minimum: 1 },
          { kind: 'specialty_count', specialty: 'rupture', minimum: 1 },
        ],
      },
      description: '需要强攻或命破队友承接失衡期终结技转换。',
    },
    evidence: [dialynGuide, yixuanLuciaDialynSeed],
  },
  {
    agentId: 'agent-ye-shunguang',
    name: '叶瞬光',
    releaseState: 'released',
    specialty: 'damage',
    faction: '云岿山',
    attribute: 'physical',
    fieldTimeDemand: 0.8,
    produces: ['qingming_sword_force', 'enlightened_mind', 'ether_veil_verdict'],
    consumes: ['qingming_sword_force', 'ether_veil'],
    effects: [{ tag: 'veil_vulnerability', recipient: 'enemy' }],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
          { kind: 'specialty_count', specialty: 'defense', minimum: 1 },
        ],
      },
      description: '需要支援或防护队友承接帷幕与剑势循环。',
    },
    evidence: [yeGuide, sproutAdoption],
  },
  {
    agentId: 'agent-zhao',
    name: '照',
    releaseState: 'released',
    specialty: 'defense',
    faction: '坎卜斯黑枝',
    attribute: 'ice',
    fieldTimeDemand: 0.15,
    produces: ['ether_veil', 'team_attack', 'team_damage'],
    consumes: [],
    effects: [
      { tag: 'team_attack', recipient: 'team' },
      { tag: 'team_damage', recipient: 'team' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'damage', minimum: 1 },
          { kind: 'specialty_count', specialty: 'anomaly', minimum: 1 },
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
        ],
      },
      description: '需要强攻、异常或支援队友。',
    },
    evidence: [zhaoGuide, yeGuide],
  },
  {
    agentId: 'agent-aria',
    name: '爱芮',
    releaseState: 'released',
    specialty: 'anomaly',
    faction: '妄想天使',
    attribute: 'ether',
    fieldTimeDemand: 0.65,
    produces: ['ether_anomaly', 'anomaly_driver', 'fandom', 'perfect_pitch', 'abloom'],
    consumes: ['fandom'],
    effects: [{ tag: 'abloom_damage', recipient: 'enemy' }],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'stun', minimum: 1 },
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
          { kind: 'faction_count', faction: '妄想天使', minimum: 2 },
          { kind: 'specialty_count', specialty: 'anomaly', minimum: 2 },
        ],
      },
      description: '需要击破、支援、同阵营或其他异常队友。',
    },
    evidence: [
      ariaGuide,
      sunnaGuide,
      yuzuhaGuide,
      {
        sourceId: 'nanoka-3.1-aria-1501-additional-ability',
        gameVersion: '3.1',
        status: 'candidate',
        locator:
          'https://static.nanoka.cc/zzz/3.1/zh/character/1501.json; passive.level.1501049.desc[1] (core level 1, no potential); sha256=d2610095c6d441de080800a6a90399344db6c9f0734c571e8456eadd3b6646a7; corroborates miyoushe77029270/op29 version update',
      },
    ],
  },
  {
    agentId: 'agent-sunna',
    name: '千夏',
    releaseState: 'released',
    specialty: 'support',
    faction: '妄想天使',
    attribute: 'physical',
    fieldTimeDemand: 0.15,
    produces: ['cat_gaze', 'claw_sharpener', 'ether_veil', 'team_attack', 'stun_multiplier'],
    consumes: ['claw_sharpener'],
    effects: [
      { tag: 'team_attack', recipient: 'team' },
      { tag: 'stun_multiplier', recipient: 'enemy' },
      { tag: 'cat_gaze', recipient: 'enemy' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'damage', minimum: 1 },
          { kind: 'faction_count', faction: '妄想天使', minimum: 2 },
        ],
      },
      description: '需要强攻或同阵营队友。',
    },
    evidence: [sunnaGuide],
  },
  {
    agentId: 'agent-yuzuha',
    name: '柚叶',
    releaseState: 'released',
    specialty: 'support',
    faction: '怪啖屋',
    attribute: 'physical',
    fieldTimeDemand: 0.15,
    produces: ['sugar_points', 'anomaly_amplification', 'disorder_amplification', 'aftershock'],
    consumes: ['sugar_points'],
    effects: [
      { tag: 'anomaly_amplification', recipient: 'team' },
      { tag: 'disorder_amplification', recipient: 'team' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'anomaly', minimum: 1 },
          { kind: 'faction_count', faction: '怪啖屋', minimum: 2 },
        ],
      },
      description: '需要异常或同阵营队友。',
    },
    evidence: [yuzuhaGuide],
  },
  {
    agentId: 'agent-promeia',
    name: '普罗米娅',
    releaseState: 'released',
    specialty: 'anomaly',
    faction: '坎卜斯黑枝',
    attribute: 'ice',
    fieldTimeDemand: 0.65,
    produces: ['ice_anomaly', 'anomaly_driver', 'corrosive_chill', 'trial_by_cold', 'abloom'],
    consumes: ['trial_by_cold'],
    effects: [{ tag: 'abloom_damage', recipient: 'enemy' }],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'anomaly', minimum: 2 },
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
        ],
      },
      description: '需要异常或支援队友。',
    },
    evidence: [promeiaGuide, nangongGuide, yuzuhaGuide],
  },
  {
    agentId: 'agent-nangong',
    name: '南宫羽',
    releaseState: 'released',
    specialty: 'stun',
    faction: '妄想天使',
    attribute: 'ether',
    fieldTimeDemand: 0.45,
    produces: [
      'downbeats',
      'dance_prowess',
      'stun_window',
      'misstep',
      'polarity_disorder',
      'vibrato',
    ],
    consumes: ['downbeats', 'dance_prowess'],
    effects: [
      { tag: 'stun_multiplier', recipient: 'enemy' },
      { tag: 'anomaly_amplification', recipient: 'team' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'anomaly', minimum: 1 },
          { kind: 'faction_count', faction: '妄想天使', minimum: 2 },
        ],
      },
      description: '需要异常或同阵营队友闭合极性紊乱。',
    },
    evidence: [nangongGuide, promeiaGuide],
  },
  {
    agentId: 'agent-pyrois',
    name: '佩洛伊斯',
    releaseState: 'released',
    specialty: 'damage',
    faction: '法厄同',
    attribute: 'ether',
    fieldTimeDemand: 0.75,
    produces: ['celestial_light', 'chain_burst', 'ultimate_cycle'],
    consumes: ['celestial_light', 'stun_window'],
    effects: [],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'stun', minimum: 1 },
          { kind: 'specialty_count', specialty: 'support', minimum: 1 },
        ],
      },
      description: '需要击破或支援队友承接连携爆发。',
    },
    evidence: [pyroisGuide, normaTeamGuide],
  },
  {
    agentId: 'agent-norma',
    name: '诺姆',
    releaseState: 'released',
    specialty: 'stun',
    faction: '罗斯凯利法·外务筹策局',
    attribute: 'fire',
    fieldTimeDemand: 0.4,
    produces: ['preheated_chamber', 'chain_attack_refill', 'tech_divide', 'stun_window'],
    consumes: ['preheated_chamber'],
    effects: [
      { tag: 'stun_multiplier', recipient: 'enemy' },
      { tag: 'team_damage', recipient: 'team' },
    ],
    additionalAbility: {
      status: 'modeled',
      predicate: {
        kind: 'any',
        predicates: [
          { kind: 'specialty_count', specialty: 'damage', minimum: 1 },
          { kind: 'specialty_count', specialty: 'rupture', minimum: 1 },
          { kind: 'faction_count', faction: '罗斯凯利法·外务筹策局', minimum: 2 },
        ],
      },
      description: '需要强攻、命破或同阵营队友。',
    },
    evidence: [normaTeamGuide, ultraJakeGuide],
  },
]
