import type { GameData31DeltaEntry } from './gameData31Delta'
import { checkedAt, announcementUrl, deadlyAssaultUrl } from './gameData31SourceGraph'
export const deltaEntriesCore: GameData31DeltaEntry[] = [
  {
    id: 'official-3.1-current-version',
    domain: 'combat_rule',
    effect: 'change',
    status: 'formal',
    displayName: '当前正式版本 3.1',
    sourceUrl: announcementUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165249-2026-07-17',
    licenseBoundary: '仅保存官方版本与日期事实。',
    affectedCalculationKinds: ['guidance', 'warehouse', 'damage', 'rotation'],
    note: '3.1 是当前运行版本；字段可信度仍逐项判断。',
  },
  {
    id: 'official-3.1-agent-remielle',
    domain: 'agent',
    effect: 'add',
    status: 'formal',
    displayName: '蕾米埃尔（官方公告新增代理人）',
    sourceUrl: announcementUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165249-2026-07-17',
    licenseBoundary: '官方公告只用于版本内新增身份事实；稳定游戏 ID 与战斗字段另行逐项核验。',
    affectedCalculationKinds: ['guidance', 'warehouse', 'damage'],
    note: '新增身份是 formal；非官方稳定 ID 与数值仍保持 candidate/missing。',
  },
  {
    id: 'official-3.1-agent-sigrid',
    domain: 'agent',
    effect: 'add',
    status: 'formal',
    displayName: 'Sigrid（官方前瞻新增代理人）',
    sourceUrl: announcementUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165248-2026-07-17',
    licenseBoundary: '官方前瞻只确认版本内新增身份；中文名、稳定 ID 与战斗字段逐项核验。',
    affectedCalculationKinds: ['guidance', 'warehouse', 'damage'],
    note: '新增身份是 formal；其余字段不随版本上线自动升格。',
  },
  {
    id: 'official-3.1-wengine-fields',
    domain: 'wengine',
    effect: 'add',
    status: 'missing',
    displayName: '3.1 新增音擎战斗字段',
    sourceUrl: announcementUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165249-2026-07-17',
    licenseBoundary: '公告不提供逐把稳定 ID、基础属性或被动。',
    affectedCalculationKinds: ['guidance', 'warehouse', 'damage'],
    note: '等待同版本官方图鉴或可核验游戏内字段。',
  },
  {
    id: 'official-3.1-bangboo-fields',
    domain: 'bangboo',
    effect: 'add',
    status: 'missing',
    displayName: '3.1 邦布战斗字段',
    sourceUrl: announcementUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165249-2026-07-17',
    licenseBoundary: '当前官方公告未提供可归一化的邦布数值字段。',
    affectedCalculationKinds: ['guidance', 'warehouse', 'damage'],
    note: '候选游戏证据可读，但不能自动成为 formal。',
  },
  {
    id: 'official-3.1-drive-disc-fields',
    domain: 'drive_disc_set',
    effect: 'change',
    status: 'missing',
    displayName: '3.1 驱动盘套装与词条规则',
    sourceUrl: announcementUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165249-2026-07-17',
    licenseBoundary: '当前公告没有逐套装/词条规则。',
    affectedCalculationKinds: ['warehouse', 'damage'],
    note: '3.0 未受影响规则连续适用；3.1 新套装字段保持 candidate/missing。',
  },
  {
    id: 'official-3.1-deadly-assault',
    domain: 'enemy_mode',
    effect: 'change',
    status: 'formal',
    displayName: '3.1 危局绝境模式范围',
    sourceUrl: deadlyAssaultUrl,
    sourceVersion: '3.1',
    sourceCheckedAt: checkedAt,
    sourceContentIdentity: 'official-news-165369-2026-07-27',
    licenseBoundary: '官方系统说明只证明玩法范围；不提供固定敌人 DEF/RES/失衡和轮换完整字段。',
    affectedCalculationKinds: ['rotation', 'damage'],
    note: '范围变化是 formal；危局数值上下文仍 missing，相关结果 stale。',
  },
]
