// id, name, role, externalId, rarity, attribute, faction, release status
export const agentCatalog = [
  ['agent-anby', '安比', 'stun', '1011', 'A', 'electric', '狡兔屋', 'released'],
  ['agent-nekomata', '猫又', 'damage', '1021', 'S', 'physical', '狡兔屋', 'released'],
  ['agent-nicole', '妮可', 'support', '1031', 'A', 'ether', '狡兔屋', 'released'],
  ['agent-soldier-11', '「11号」', 'damage', '1041', 'S', 'fire', '新艾利都防卫军', 'released'],
  ['agent-yidhari', '伊德海莉', 'rupture', '1051', 'S', 'ice', '怪啖屋', 'released'],
  ['agent-corin', '可琳', 'damage', '1061', 'A', 'physical', '维多利亚家政', 'released'],
  ['agent-caesar', '凯撒', 'defense', '1071', 'S', 'physical', '卡吕冬之子', 'released'],
  ['agent-billy', '比利', 'damage', '1081', 'A', 'physical', '狡兔屋', 'released'],
  ['agent-miyabi', '星见雅', 'anomaly', '1091', 'S', 'ice', '对空洞特别行动部第六课', 'released'],
  ['agent-koleda', '珂蕾妲', 'stun', '1101', 'S', 'fire', '白祇重工', 'released'],
  ['agent-anton', '安东', 'damage', '1111', 'A', 'electric', '白祇重工', 'released'],
  ['agent-ben', '本', 'defense', '1121', 'A', 'fire', '白祇重工', 'released'],
  ['agent-soukaku', '苍角', 'support', '1131', 'A', 'ice', '对空洞特别行动部第六课', 'released'],
  ['agent-lycaon', '莱卡恩', 'stun', '1141', 'S', 'ice', '维多利亚家政', 'released'],
  ['agent-lucy', '露西', 'support', '1151', 'A', 'fire', '卡吕冬之子', 'released'],
  ['agent-lighter', '莱特', 'stun', '1161', 'S', 'fire', '卡吕冬之子', 'released'],
  ['agent-burnice', '柏妮思', 'anomaly', '1171', 'S', 'fire', '卡吕冬之子', 'released'],
  ['agent-grace', '格莉丝', 'anomaly', '1181', 'S', 'electric', '白祇重工', 'released'],
  ['agent-ellen', '艾莲', 'damage', '1191', 'S', 'ice', '维多利亚家政', 'released'],
  [
    'agent-harumasa',
    '悠真',
    'damage',
    '1201',
    'S',
    'electric',
    '对空洞特别行动部第六课',
    'released',
  ],
  ['agent-rina', '丽娜', 'support', '1211', 'S', 'electric', '维多利亚家政', 'released'],
  ['agent-yanagi', '柳', 'anomaly', '1221', 'S', 'electric', '对空洞特别行动部第六课', 'released'],
  ['agent-zhu-yuan', '朱鸢', 'damage', '1241', 'S', 'ether', '新艾利都治安局', 'released'],
  ['agent-qingyi', '青衣', 'stun', '1251', 'S', 'electric', '新艾利都治安局', 'released'],
  ['agent-jane', '简', 'anomaly', '1261', 'S', 'physical', '新艾利都治安局', 'released'],
  ['agent-seth', '赛斯', 'defense', '1271', 'A', 'electric', '新艾利都治安局', 'released'],
  ['agent-piper', '派派', 'anomaly', '1281', 'A', 'physical', '卡吕冬之子', 'released'],
  ['agent-hugo', '雨果', 'damage', '1291', 'S', 'ice', '反舌鸟', 'released'],
  [
    'agent-orphie-magus',
    '奥菲丝&「鬼火」',
    'damage',
    '1301',
    'S',
    'fire',
    '新艾利都防卫军',
    'released',
  ],
  ['agent-astra', '耀嘉音', 'support', '1311', 'S', 'ether', '天琴座', 'released'],
  ['agent-evelyn', '伊芙琳', 'damage', '1321', 'S', 'fire', '天琴座', 'released'],
  ['agent-vivian', '薇薇安', 'anomaly', '1331', 'S', 'ether', '反舌鸟', 'released'],
  ['agent-zhao', '照', 'defense', '1341', 'S', 'ice', '坎卜斯黑枝', 'released'],
  ['agent-pulchra', '波可娜', 'stun', '1351', 'A', 'physical', '卡吕冬之子', 'released'],
  ['agent-trigger', '「扳机」', 'stun', '1361', 'S', 'electric', '新艾利都防卫军', 'released'],
  ['agent-yixuan', '仪玄', 'rupture', '1371', 'S', 'ether', '云岿山', 'released'],
  [
    'agent-soldier-0-anby',
    '零号·安比',
    'damage',
    '1381',
    'S',
    'electric',
    '新艾利都防卫军',
    'released',
  ],
  ['agent-ju-fufu', '橘福福', 'stun', '1391', 'S', 'fire', '云岿山', 'released'],
  ['agent-alice', '爱丽丝', 'anomaly', '1401', 'S', 'physical', '怪啖屋', 'released'],
  ['agent-yuzuha', '柚叶', 'support', '1411', 'S', 'physical', '怪啖屋', 'released'],
  ['agent-pan-yinhu', '潘引壶', 'defense', '1421', 'A', 'physical', '云岿山', 'released'],
  ['agent-ye-shunguang', '叶瞬光', 'damage', '1431', 'S', 'physical', '云岿山', 'released'],
  ['agent-manato', '狛野真斗', 'rupture', '1441', 'A', 'fire', '怪啖屋', 'released'],
  ['agent-lucia', '卢西娅', 'support', '1451', 'S', 'ether', '怪啖屋', 'released'],
  ['agent-seed', '「席德」', 'damage', '1461', 'S', 'electric', '新艾利都防卫军', 'released'],
  ['agent-banyue', '般岳', 'rupture', '1471', 'S', 'fire', '坎卜斯黑枝', 'released'],
  ['agent-dialyn', '琉音', 'stun', '1481', 'S', 'physical', '坎卜斯黑枝', 'released'],
  ['agent-sunna', '千夏', 'support', '1491', 'S', 'physical', '妄想天使', 'released'],
  ['agent-aria', '爱芮', 'anomaly', '1501', 'S', 'ether', '妄想天使', 'released'],
  ['agent-nangong', '南宫羽', 'stun', '1511', 'S', 'ether', '妄想天使', 'released'],
  ['agent-cissia', '希希芙', 'damage', '1521', 'S', 'electric', '新艾利都治安局', 'released'],
  ['agent-starlight-billy', '星徽·比利', 'rupture', '1531', 'S', 'physical', '狡兔屋', 'released'],
  ['agent-promeia', '普罗米娅', 'anomaly', '1541', 'S', 'ice', '坎卜斯黑枝', 'released'],
  ['agent-pyrois', '佩洛伊斯', 'damage', '1551', 'S', 'ether', '法厄同', 'released'],
  ['agent-velina', '维琳娜', 'anomaly', '1561', 'S', 'wind', '罗斯凯利法·外务筹策局', 'released'],
  ['agent-norma', '诺姆', 'stun', '1571', 'S', 'fire', '罗斯凯利法·外务筹策局', 'released'],
] as const

// id, name, externalId, rarity, release status
export const bangbooCatalog = [
  ['bangboo-penguinboo', '企鹅布', '53001', 'A', 'released'],
  ['bangboo-luckyboo', '招财布', '53002', 'A', 'released'],
  ['bangboo-exploreboo', '寻宝布', '53003', 'A', 'released'],
  ['bangboo-sumoboo', '扑击布', '53004', 'A', 'released'],
  ['bangboo-paperboo', '纸壳布', '53005', 'A', 'released'],
  ['bangboo-bagboo', '纸袋布', '53006', 'A', 'released'],
  ['bangboo-cryboo', '泪眼布', '53007', 'A', 'released'],
  ['bangboo-avocaboo', '果核布', '53008', 'A', 'released'],
  ['bangboo-boollseye', '飞靶布', '53009', 'A', 'released'],
  ['bangboo-electroboo', '电击布', '53010', 'A', 'released'],
  ['bangboo-magnetiboo', '磁力布', '53011', 'A', 'released'],
  ['bangboo-booressure', '气压布', '53012', 'A', 'released'],
  ['bangboo-baddieboo', '不良布', '53013', 'A', 'released'],
  ['bangboo-overtimeboo', '加班布', '53014', 'A', 'released'],
  ['bangboo-brawlerboo', '格斗布', '53015', 'A', 'released'],
  ['bangboo-excaliboo', '圣剑布', '53016', 'A', 'released'],
  ['bangboo-knightboo', '骑士布', '53017', 'A', 'released'],
  ['bangboo-bild-n-boolok', '乐玩布', '53019', 'A', 'released'],
  ['bangboo-booltergeist', '幽浮布', '53021', 'A', 'released'],
  ['bangboo-sharkboo', '鲨牙布', '54001', 'S', 'released'],
  ['bangboo-safety', '阿全', '54002', 'S', 'released'],
  ['bangboo-devilboo', '恶魔布', '54003', 'A', 'released'],
  ['bangboo-butler', '巴特勒', '54004', 'S', 'released'],
  ['bangboo-amillion', '艾米莉安', '54005', 'S', 'released'],
  ['bangboo-rocketboo', '飚速布', '54006', 'S', 'released'],
  ['bangboo-plugboo', '插头布', '54008', 'S', 'released'],
  ['bangboo-resonaboo', '共鸣布', '54009', 'S', 'released'],
  ['bangboo-biggest-fan', '阿饭', '54010', 'S', 'released'],
  ['bangboo-red-moccus', '赤红莫库斯', '54011', 'S', 'released'],
  ['bangboo-officer-cui', '阿崔巡查', '54012', 'S', 'released'],
  ['bangboo-bangvolver', '左轮布', '54013', 'S', 'released'],
  ['bangboo-agent-gulliver', '格列佛探员', '54014', 'S', 'released'],
  ['bangboo-snap', '咔嚓仔', '54015', 'S', 'released'],
  ['bangboo-robin', '罗宾', '54016', 'S', 'released'],
  ['bangboo-belion', '狮耶', '54017', 'S', 'released'],
  ['bangboo-miss-esme', '艾丝弥小姐', '54018', 'S', 'released'],
  ['bangboo-mercury', '「墨丘利」', '54019', 'S', 'released'],
  ['bangboo-birkblick', '比克布利克', '54020', 'S', 'released'],
  ['bangboo-sprout', '芽芽', '54021', 'S', 'released'],
  ['bangboo-ultra-jake', '超极杰克', '54022', 'S', 'released'],
] as const
