export const teamTemplates = [
  {
    id: 'girtablullu-wind-anomaly',
    bossId: 'girtablullu',
    name: '风化异常循环',
    agentIds: ['agent-velina', 'agent-burnice', 'agent-yuzuha'],
    bangbooId: 'bangboo-ultra-jake',
    confidence: 'high',
    templatePriority: 96,
    minimums: { level: 60, mindscape: 0, completeness: 'partial' },
    reasons: ['命中风弱点', '维琳娜当前版本资料完整', '当期社区实战可交叉核对'],
    gameVersion: '3.0',
    rotationId: 'deadly-assault-3.0-2026-06-19',
    mode: 'deadly_assault',
    assumptions: { mindscape: 'M0+', wEngine: '未限定', cycle: '风化异常循环' },
    buffs: [
      {
        name: '北风',
        trigger: '风属性/异常循环',
        coverage: 0.8,
        source: '候选提示，不参与伤害计算',
      },
    ],
    sources: ['官方 3.0 更新说明', 'Prydwen 当期统计', 'HoYoLAB 3.0.1 实战'],
    updatedAt: '2026-06-25T00:00:00.000Z',
  },
  {
    id: 'marionette-ice-window',
    bossId: 'notorious-marionette',
    name: '冰属性失衡窗口',
    agentIds: ['agent-miyabi', 'agent-astra', 'agent-nangong'],
    bangbooId: 'bangboo-sharkboo',
    confidence: 'medium',
    templatePriority: 90,
    minimums: { level: 60, mindscape: 0, completeness: 'partial' },
    reasons: ['命中冰弱点', '击破与爆发窗口匹配', '技能倍率仍需账号级复核'],
    gameVersion: '3.0',
    rotationId: 'deadly-assault-3.0-2026-06-19',
    mode: 'deadly_assault',
    assumptions: { mindscape: 'M0+', wEngine: '未限定', cycle: '失衡窗口爆发' },
    buffs: [
      { name: '猛攻', trigger: '爆发窗口', coverage: 0.65, source: '候选提示，不参与伤害计算' },
    ],
    sources: ['Prydwen 当期统计'],
    updatedAt: '2026-06-23T00:00:00.000Z',
  },
  {
    id: 'thrall-chain-parry',
    bossId: 'ye-shiyuan-thrall',
    name: '链式招架直伤',
    agentIds: ['agent-ye-shunguang', 'agent-sunna', 'agent-zhao'],
    bangbooId: 'bangboo-robin',
    confidence: 'medium',
    templatePriority: 88,
    minimums: { level: 60, mindscape: 0, completeness: 'partial' },
    reasons: ['命中冰/风弱点', '当期实战队伍有依据', '机制分换算尚未验证'],
    gameVersion: '3.0',
    rotationId: 'deadly-assault-3.0-2026-06-19',
    mode: 'deadly_assault',
    assumptions: { mindscape: 'M0+', wEngine: '未限定', cycle: '链式招架直伤' },
    buffs: [
      { name: '猛攻', trigger: '链式招架', coverage: 0.7, source: '候选提示，不参与伤害计算' },
    ],
    sources: ['HoYoLAB 3.0.1 实战', 'Prydwen 当期统计'],
    updatedAt: '2026-06-23T00:00:00.000Z',
  },
  {
    id: 'girtablullu-ice-anomaly',
    bossId: 'girtablullu',
    name: '冰异常替代候选',
    agentIds: ['agent-promeia', 'agent-velina', 'agent-yuzuha'],
    bangbooId: 'bangboo-ultra-jake',
    confidence: 'medium',
    templatePriority: 82,
    minimums: { level: 60, mindscape: 0, completeness: 'partial' },
    reasons: ['当期统计存在普罗米娅/维琳娜组合', '未验证完整循环伤害'],
    gameVersion: '3.0',
    rotationId: 'deadly-assault-3.0-2026-06-19',
    mode: 'deadly_assault',
    assumptions: { mindscape: 'M0+', wEngine: '未限定', cycle: '异常交替' },
    buffs: [],
    sources: ['Prydwen 当期统计'],
    updatedAt: '2026-06-23T00:00:00.000Z',
  },
  {
    id: 'marionette-yidhari-window',
    bossId: 'notorious-marionette',
    name: '冰破失衡替代候选',
    agentIds: ['agent-yidhari', 'agent-dialyn', 'agent-astra'],
    bangbooId: 'bangboo-sharkboo',
    confidence: 'medium',
    templatePriority: 84,
    minimums: { level: 60, mindscape: 0, completeness: 'partial' },
    reasons: ['命中冰弱点', '候选来自当期实战交叉样本'],
    gameVersion: '3.0',
    rotationId: 'deadly-assault-3.0-2026-06-19',
    mode: 'deadly_assault',
    assumptions: { mindscape: 'M0+', wEngine: '未限定', cycle: '失衡窗口' },
    buffs: [],
    sources: ['HoYoLAB 3.0.1 实战'],
    updatedAt: '2026-06-18T00:00:00.000Z',
  },
  {
    id: 'thrall-yidhari-chain',
    bossId: 'ye-shiyuan-thrall',
    name: '链式招架替代候选',
    agentIds: ['agent-ye-shunguang', 'agent-dialyn', 'agent-sunna'],
    bangbooId: 'bangboo-robin',
    confidence: 'medium',
    templatePriority: 83,
    minimums: { level: 60, mindscape: 0, completeness: 'partial' },
    reasons: ['当期实战存在叶瞬光/琉音组合', '机制分仍不参与计算'],
    gameVersion: '3.0',
    rotationId: 'deadly-assault-3.0-2026-06-19',
    mode: 'deadly_assault',
    assumptions: { mindscape: 'M0+', wEngine: '未限定', cycle: '链式招架' },
    buffs: [],
    sources: ['HoYoLAB 3.0.1 实战'],
    updatedAt: '2026-06-18T00:00:00.000Z',
  },
] as const
