export const current31Shiyu313ObservedCalibrationContractId =
  'soda-current-3.1.3-shiyu-observed-calibration/v1' as const

export type Current31ShiyuStage = '5-1' | '5-2' | '5-3'

export type Current31ShiyuObservedTeam = {
  observationId: string
  stage: Current31ShiyuStage
  split: 'calibration' | 'holdout'
  rank: number
  appearanceRatePercent: number
  averageScore: number
  memberIds: readonly [string, string, string]
}

const observedTeams: readonly Current31ShiyuObservedTeam[] = [
  {
    observationId: '3.1.3-5-1-r1',
    stage: '5-1',
    split: 'calibration',
    rank: 1,
    appearanceRatePercent: 26.98,
    averageScore: 38037,
    memberIds: ['agent-remielle', 'agent-jane', 'agent-velina'],
  },
  {
    observationId: '3.1.3-5-1-r2',
    stage: '5-1',
    split: 'calibration',
    rank: 2,
    appearanceRatePercent: 7.53,
    averageScore: 38185,
    memberIds: ['agent-remielle', 'agent-alice', 'agent-velina'],
  },
  {
    observationId: '3.1.3-5-1-r3',
    stage: '5-1',
    split: 'calibration',
    rank: 3,
    appearanceRatePercent: 7.51,
    averageScore: 36836,
    memberIds: ['agent-remielle', 'agent-promeia', 'agent-velina'],
  },
  {
    observationId: '3.1.3-5-1-r4',
    stage: '5-1',
    split: 'calibration',
    rank: 4,
    appearanceRatePercent: 6.39,
    averageScore: 37949,
    memberIds: ['agent-remielle', 'agent-aria', 'agent-velina'],
  },
  {
    observationId: '3.1.3-5-1-r5',
    stage: '5-1',
    split: 'calibration',
    rank: 5,
    appearanceRatePercent: 2.76,
    averageScore: 30416,
    memberIds: ['agent-ye-shunguang', 'agent-sunna', 'agent-zhao'],
  },
  {
    observationId: '3.1.3-5-1-r6',
    stage: '5-1',
    split: 'calibration',
    rank: 6,
    appearanceRatePercent: 2.31,
    averageScore: 36877,
    memberIds: ['agent-remielle', 'agent-burnice', 'agent-velina'],
  },
  {
    observationId: '3.1.3-5-1-r7',
    stage: '5-1',
    split: 'calibration',
    rank: 7,
    appearanceRatePercent: 2.22,
    averageScore: 37812,
    memberIds: ['agent-remielle', 'agent-piper', 'agent-velina'],
  },
  {
    observationId: '3.1.3-5-1-r8',
    stage: '5-1',
    split: 'calibration',
    rank: 8,
    appearanceRatePercent: 1.8,
    averageScore: 30415,
    memberIds: ['agent-remielle', 'agent-jane', 'agent-vivian'],
  },
  {
    observationId: '3.1.3-5-1-r9',
    stage: '5-1',
    split: 'calibration',
    rank: 9,
    appearanceRatePercent: 1.71,
    averageScore: 32432,
    memberIds: ['agent-jane', 'agent-velina', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-1-r10',
    stage: '5-1',
    split: 'calibration',
    rank: 10,
    appearanceRatePercent: 1.13,
    averageScore: 32149,
    memberIds: ['agent-remielle', 'agent-alice', 'agent-jane'],
  },
  {
    observationId: '3.1.3-5-2-r1',
    stage: '5-2',
    split: 'calibration',
    rank: 1,
    appearanceRatePercent: 14.98,
    averageScore: 33396,
    memberIds: ['agent-ye-shunguang', 'agent-sunna', 'agent-zhao'],
  },
  {
    observationId: '3.1.3-5-2-r2',
    stage: '5-2',
    split: 'calibration',
    rank: 2,
    appearanceRatePercent: 13.27,
    averageScore: 31281,
    memberIds: ['agent-aria', 'agent-nangong', 'agent-sunna'],
  },
  {
    observationId: '3.1.3-5-2-r3',
    stage: '5-2',
    split: 'calibration',
    rank: 3,
    appearanceRatePercent: 9.66,
    averageScore: 28953,
    memberIds: ['agent-yixuan', 'agent-dialyn', 'agent-lucia'],
  },
  {
    observationId: '3.1.3-5-2-r4',
    stage: '5-2',
    split: 'calibration',
    rank: 4,
    appearanceRatePercent: 8.9,
    averageScore: 35696,
    memberIds: ['agent-ye-shunguang', 'agent-dialyn', 'agent-sunna'],
  },
  {
    observationId: '3.1.3-5-2-r5',
    stage: '5-2',
    split: 'calibration',
    rank: 5,
    appearanceRatePercent: 6.84,
    averageScore: 30867,
    memberIds: ['agent-ye-shunguang', 'agent-dialyn', 'agent-zhao'],
  },
  {
    observationId: '3.1.3-5-2-r6',
    stage: '5-2',
    split: 'calibration',
    rank: 6,
    appearanceRatePercent: 5,
    averageScore: 32396,
    memberIds: ['agent-miyabi', 'agent-nangong', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-2-r7',
    stage: '5-2',
    split: 'calibration',
    rank: 7,
    appearanceRatePercent: 3.43,
    averageScore: 27268,
    memberIds: ['agent-yixuan', 'agent-ju-fufu', 'agent-lucia'],
  },
  {
    observationId: '3.1.3-5-2-r8',
    stage: '5-2',
    split: 'calibration',
    rank: 8,
    appearanceRatePercent: 2.91,
    averageScore: 31575,
    memberIds: ['agent-aria', 'agent-nangong', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-2-r9',
    stage: '5-2',
    split: 'calibration',
    rank: 9,
    appearanceRatePercent: 1.56,
    averageScore: 28962,
    memberIds: ['agent-alice', 'agent-vivian', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-2-r10',
    stage: '5-2',
    split: 'calibration',
    rank: 10,
    appearanceRatePercent: 1.5,
    averageScore: 28463,
    memberIds: ['agent-ye-shunguang', 'agent-astra', 'agent-zhao'],
  },
  {
    observationId: '3.1.3-5-3-r1',
    stage: '5-3',
    split: 'holdout',
    rank: 1,
    appearanceRatePercent: 17.89,
    averageScore: 36527,
    memberIds: ['agent-miyabi', 'agent-nangong', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-3-r2',
    stage: '5-3',
    split: 'holdout',
    rank: 2,
    appearanceRatePercent: 6.38,
    averageScore: 29213,
    memberIds: ['agent-yixuan', 'agent-dialyn', 'agent-lucia'],
  },
  {
    observationId: '3.1.3-5-3-r3',
    stage: '5-3',
    split: 'holdout',
    rank: 3,
    appearanceRatePercent: 5.47,
    averageScore: 35183,
    memberIds: ['agent-ye-shunguang', 'agent-sunna', 'agent-zhao'],
  },
  {
    observationId: '3.1.3-5-3-r4',
    stage: '5-3',
    split: 'holdout',
    rank: 4,
    appearanceRatePercent: 5.19,
    averageScore: 29719,
    memberIds: ['agent-miyabi', 'agent-vivian', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-3-r5',
    stage: '5-3',
    split: 'holdout',
    rank: 5,
    appearanceRatePercent: 4.87,
    averageScore: 32291,
    memberIds: ['agent-ye-shunguang', 'agent-dialyn', 'agent-zhao'],
  },
  {
    observationId: '3.1.3-5-3-r6',
    stage: '5-3',
    split: 'holdout',
    rank: 6,
    appearanceRatePercent: 3.19,
    averageScore: 27713,
    memberIds: ['agent-yixuan', 'agent-ju-fufu', 'agent-lucia'],
  },
  {
    observationId: '3.1.3-5-3-r7',
    stage: '5-3',
    split: 'holdout',
    rank: 7,
    appearanceRatePercent: 2.42,
    averageScore: 36403,
    memberIds: ['agent-ye-shunguang', 'agent-dialyn', 'agent-sunna'],
  },
  {
    observationId: '3.1.3-5-3-r8a',
    stage: '5-3',
    split: 'holdout',
    rank: 8,
    appearanceRatePercent: 1.75,
    averageScore: 34250,
    memberIds: ['agent-sigrid', 'agent-norma', 'agent-astra'],
  },
  {
    observationId: '3.1.3-5-3-r8b',
    stage: '5-3',
    split: 'holdout',
    rank: 8,
    appearanceRatePercent: 1.75,
    averageScore: 29124,
    memberIds: ['agent-miyabi', 'agent-yanagi', 'agent-yuzuha'],
  },
  {
    observationId: '3.1.3-5-3-r10',
    stage: '5-3',
    split: 'holdout',
    rank: 10,
    appearanceRatePercent: 1.48,
    averageScore: 33041,
    memberIds: ['agent-miyabi', 'agent-nangong', 'agent-astra'],
  },
] as const

export const current31Shiyu313ObservedCalibration = Object.freeze({
  contract: current31Shiyu313ObservedCalibrationContractId,
  gameVersion: '3.1.3',
  observedAt: '2026-08-29',
  source: {
    sourceId: 'prydwen-shiyu-defense-3.1.3-2026-08-29',
    url: 'https://www.prydwen.gg/zenless/shiyu-defense',
    reportedPlayerCount: 19_512,
    configuration: 'M0 S-rank agents and all W-Engines',
    rankMeaning: 'page rank within the selected stage and configuration',
    scoreMeaning: 'average in-game score reported by the source',
  },
  observations: observedTeams,
  calibration: observedTeams.filter((item) => item.split === 'calibration'),
  holdout: observedTeams.filter((item) => item.split === 'holdout'),
  sourceIndependentHoldoutCount: 0,
  boundary:
    '该数据是场景化实战观测，可用于现实校准和留出回归；不直接进入伤害公式、不代表跨场景全序、不代表账号培养优先级。当前 holdout 与 calibration 来自同一站点和同一周期，不得冒充 source-independent holdout。',
})
