import displayProjection from './visual-assets-display.v1.json'
import { visualAssetManifestSchema } from './visualAssetSchemas'

/**
 * Public binding: the generated display projection of the same manifest. It keeps identity, display
 * name and the download/cache facts the existing image pipeline needs and leaves the internal
 * source, licence, attribution and review ledger on the desktop side. Generated by
 * `scripts/generate-visual-asset-display-projection.mjs` and enforced by the catalog integrity gate.
 */
export default visualAssetManifestSchema.parse(displayProjection)
