/** Generated by scripts/generate-public-display-projections.mjs; display identity only. */
export const publicVersionIdentity = {
  id: 'current-version-projection-3.2',
  gameVersion: '3.2',
  packageId: 'game-base-3.2.0-current',
  packageVersion: '3.2.0-current.1',
  rollbackPackageId: null,
  lifecycle: 'current',
  fieldBoundary:
    '3.2上下半是当前已采用读取版本；目录、锁定来源与兼容恢复分别绑定。current 不等于全部字段 formal；旧3.1字段、审核和存档保留原版本，精算能力仅按具名已采用模型开放。',
  adoptionId: 'current-version-adoption-3.2-phase-ii-r1',
  adoptionContentHash: 'fnv1a-34a56a5d',
  sourceCommit: '3456cd0f6f5bea10e168074502460dac2fcd6df4',
  phase: 'phase_ii',
  scopeManifestId: 'current-scope-manifest-3.2-r1',
  scopeContentHash: 'fnv1a-54fa1e79',
  directoryCoverage: {
    directoryTotal: 231,
    releasedScope: 231,
    accountOwnable: 231,
    byDomain: { agent: 60, wengine: 100, bangboo: 41, drive_disc_set: 30 },
  },
  compatibilityRecovery: {
    policyId: 'incremental-32-compatibility-recovery-v1',
    disabledCapabilityScope: '3.2_precision_only',
    preservesReleasedIdentities: true,
    preservesAccountAndSavedPlans: true,
    previousResults: 'requires_reanalysis',
    capabilityIdentity: {
      previousCommit: 'eabba1f092b282cccb3f028b7253a1db3dac5208',
      currentCommit: '3456cd0f6f5bea10e168074502460dac2fcd6df4',
      deltaSha256: 'e1625ddfe6c45e5157e01f258142bd68b9137cde1defa41b91a47c3dc4c48ce8',
      changedOldFormulaSubjects: ['agent-miyabi', 'agent-nekomata', 'agent-piper'],
      koledaChangedPotentialMinimum: 2,
    },
  },
  contentHash: 'fnv1a-55673acf',
} as const
