// Released catalog display order. Keep this presentation list in sync with the
// private source projection through publicDiscSetOrder.test.ts.
export const publicDiscSetOrder = [
  'set-34100',
  'set-34200',
  'set-wuthering-salon',
  'set-the-sky-ablaze',
  'set-bunny-in-wonderland',
  'set-notes-from-the-chained',
  'set-white-water-ballad',
  'set-shining-aria',
  'set-dawns-bloom',
  'set-moonlight-lullaby',
  'set-yunkui-tales',
  'set-king-of-the-summit',
  'set-shadow-harmony',
  'set-phaethons-melody',
  'set-branch-blade-song',
  'set-astral-voice',
  'set-chaos-jazz',
  'set-proto-punk',
  'set-woodpecker-electro',
  'set-puffer-electro',
  'set-shockstar-disco',
  'set-freedom-blues',
  'set-hormone-punk',
  'set-soul-rock',
  'set-swing-jazz',
  'set-inferno-metal',
  'set-chaotic-metal',
  'set-thunder-metal',
  'set-polar-metal',
  'set-fanged-metal',
] as const
